projeOdev/projeOdev/Controllers/DuyuruController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using projeOdev.Models;
using projeOdev.Blog;
using PagedList;

namespace projeOdev.Controllers
{
    public class DuyuruController : Controller
    {
        private hbrContext db = new hbrContext();

        // GET: /Duyuru/
        public ActionResult Index(string siralama, string currentFilter, string arama, int? page)
        {
            ViewBag.CurrentSort = siralama;
            ViewBag.NameSortParm = String.IsNullOrEmpty(siralama) ? "duyuru_azalan" : "";
            if (arama != null)
            {
                page = 1;
            }
            else { arama = currentFilter; }
            ViewBag.CurrentFilter = arama;

            var duyurular = from s in db.Duyurular
                            select s;
            if (!String.IsNullOrEmpty(arama))
            {
                duyurular = duyurular.Where(s => s.Dbaslik.ToUpper().Contains(arama.ToUpper()));
            }
            switch (siralama)
            {
                case "duyuru_azalan":
                    duyurular = duyurular.OrderByDescending(s => s.Dbaslik);
                    break;
                default:
                    duyurular = duyurular.OrderBy(s => s.Dbaslik);
                    break;
            }

            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(duyurular.ToPagedList(pageNumber, pageSize));
        }

        // GET: /Duyuru/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Duyurular duyurular = db.Duyurular.Find(id);
            if (duyurular == null)
            {
                return HttpNotFound();
            }
            return View(duyurular);
        }

        // GET: /Duyuru/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Duyuru/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DuyurularID,Dbaslik,Dicerik")] Duyurular duyurular)
        {
            if (ModelState.IsValid)
            {
                db.Duyurular.Add(duyurular);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(duyurular);
        }

        // GET: /Duyuru/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Duyurular duyurular = db.Duyurular.Find(id);
            if (duyurular == null)
            {
                return HttpNotFound();
            }
            return View(duyurular);
        }

        // POST: /Duyuru/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DuyurularID,Dbaslik,Dicerik")] Duyurular duyurular)
        {
            if (ModelState.IsValid)
            {
                db.Entry(duyurular).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(duyurular);
        }

        // GET: /Duyuru/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Duyurular duyurular = db.Duyurular.Find(id);
            if (duyurular == null)
            {
                return HttpNotFound();
            }
            return View(duyurular);
        }

        // POST: /Duyuru/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Duyurular duyurular = db.Duyurular.Find(id);
            db.Duyurular.Remove(duyurular);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

projeOdev/projeOdev/Views/Duyuru/Create.cshtml
@model projeOdev.Models.Duyurular

@{
    ViewBag.Title = "Duyuru Ekle";
}

<h2>Ekle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Duyurular</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Dbaslik, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dbaslik)
                @Html.ValidationMessageFor(model => model.Dbaslik)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dicerik, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dicerik)
                @Html.ValidationMessageFor(model => model.Dicerik)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Duyurulara Geri Dön", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

projeOdev/projeOdev/Views/Duyuru/Delete.cshtml
@model projeOdev.Models.Duyurular

@{
    ViewBag.Title = "Duyuru Sil";
}

<h2>Sil</h2>

<h3>Silmek istediğine emin misin?</h3>
<div>
    <h4>Duyurular</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Dbaslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dbaslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dicerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dicerik)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Duyurulara Geri Dön", "Index")
        </div>
    }
</div>

projeOdev/projeOdev/Views/Duyuru/Details.cshtml
@model projeOdev.Models.Duyurular

@{
    ViewBag.Title = "Duyuru Detayı";
}

<h2>Detaylar</h2>

<div>
    <h4>Duyurular</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Dbaslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dbaslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dicerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dicerik)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Düzenle", "Edit", new { id = Model.DuyurularID }) |
    @Html.ActionLink("Duyurulara Geri Dön", "Index")
</p>

projeOdev/projeOdev/Views/Duyuru/Edit.cshtml
@model projeOdev.Models.Duyurular

@{
    ViewBag.Title = "Duyuru Düzenle";
}

<h2>Düzenle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Duyurular</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.DuyurularID)

        <div class="form-group">
            @Html.LabelFor(model => model.Dbaslik, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dbaslik)
                @Html.ValidationMessageFor(model => model.Dbaslik)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dicerik, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dicerik)
                @Html.ValidationMessageFor(model => model.Dicerik)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Duyurulara Geri Dön", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

projeOdev/projeOdev/Views/Duyuru/Index.cshtml
@model PagedList.IPagedList<projeOdev.Models.Duyurular>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Duyurular";
}

<h2>Duyurular</h2>

<p>
    @Html.ActionLink("Duyuru Ekle", "Create")
</p>
@using (Html.BeginForm("Index", "Duyuru", FormMethod.Get))
{
    <p>
        Başlığa, İçeriğe Göre Arama : @Html.TextBox("Arama", ViewBag.CurrentFilter as string)
        <input type="submit" value="Ara" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Duyuru Başlığı", "Index", new { siralama = ViewBag.NameSortParm })
            @*@Html.DisplayNameFor(model => model.Dbaslik)*@
        </th>
        <th>
            Duyuru İçeriği
            @*@Html.DisplayNameFor(model => model.Dicerik)*@
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Dbaslik)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dicerik)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", new { id = item.DuyurularID }) |
                @Html.ActionLink("Detaylar", "Details", new { id = item.DuyurularID }) |
                @Html.ActionLink("Sil", "Delete", new { id = item.DuyurularID })
            </td>
        </tr>
    }

</table>
<br /> Sayfa @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))