projeOdev/projeOdev/Controllers/HaberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using projeOdev.Models;
using projeOdev.Blog;
using PagedList;

namespace projeOdev.Controllers
{
    public class HaberController : Controller
    {
        private hbrContext db = new hbrContext();

        // GET: /Haber/
        public ActionResult Index(string siralama, string currentFilter, string arama, int? page)
        {
            ViewBag.CurrentSort = siralama;
            ViewBag.NameSortParm = String.IsNullOrEmpty(siralama) ? "haber_azalan" : "";
            if (arama != null)
            {
                page = 1;
            }
            else { arama = currentFilter; }
            ViewBag.CurrentFilter = arama;
            var haberler = from s in db.Haberler
                           select s;
            if (!String.IsNullOrEmpty(arama))
            {
                haberler = haberler.Where(s => s.Hbaslik.ToUpper().Contains(arama.ToUpper()));
            }
            switch (siralama)
            {
                case "haber_azalan":
                    haberler = haberler.OrderByDescending(s => s.Hbaslik);
                    break;
                default:
                    haberler = haberler.OrderBy(s => s.Hbaslik);
                    break;
            }

            int pageSize = 2;
            int pageNumber = (page ?? 1);
            return View(haberler.ToPagedList(pageNumber, pageSize));
        }

        // GET: /Haber/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Haberler haberler = db.Haberler.Find(id);
            if (haberler == null)
            {
                return HttpNotFound();
            }
            return View(haberler);
        }

        // GET: /Haber/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Haber/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HaberlerID,Hbaslik,Hicerik")] Haberler haberler)
        {
            if (ModelState.IsValid)
            {
                db.Haberler.Add(haberler);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(haberler);
        }

        // GET: /Haber/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Haberler haberler = db.Haberler.Find(id);
            if (haberler == null)
            {
                return HttpNotFound();
            }
            return View(haberler);
        }

        // POST: /Haber/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HaberlerID,Hbaslik,Hicerik")] Haberler haberler)
        {
            if (ModelState.IsValid)
            {
                db.Entry(haberler).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(haberler);
        }

        // GET: /Haber/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Haberler haberler = db.Haberler.Find(id);
            if (haberler == null)
            {
                return HttpNotFound();
            }
            return View(haberler);
        }

        // POST: /Haber/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Haberler haberler = db.Haberler.Find(id);
            db.Haberler.Remove(haberler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

projeOdev/projeOdev/Views/Haber/Create.cshtml
@model projeOdev.Models.Haberler

@{
    ViewBag.Title = "Haber Ekle";
}

<h2>Haber Ekle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Haberler</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Hbaslik, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hbaslik)
                @Html.ValidationMessageFor(model => model.Hbaslik)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hicerik, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hicerik)
                @Html.ValidationMessageFor(model => model.Hicerik)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Haberlere Geri Dön", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

projeOdev/projeOdev/Views/Haber/Delete.cshtml
@model projeOdev.Models.Haberler

@{
    ViewBag.Title = "Haber Sil";
}

<h2>Sil</h2>

<h3>Silmek istediğine emin misin?</h3>
<div>
    <h4>Haberler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hbaslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hbaslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hicerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hicerik)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Haberlere Geri Dön", "Index")
        </div>
    }
</div>

projeOdev/projeOdev/Views/Haber/Details.cshtml
@model projeOdev.Models.Haberler

@{
    ViewBag.Title = "Haber Detayları";
}

<h2>Detaylar</h2>

<div>
    <h4>Haberler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hbaslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hbaslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hicerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hicerik)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Düzenle", "Edit", new { id = Model.HaberlerID }) |
    @Html.ActionLink("Haberlere Geri Dön", "Index")
</p>

projeOdev/projeOdev/Views/Haber/Edit.cshtml
@model projeOdev.Models.Haberler

@{
    ViewBag.Title = "Haberi Düzenle";
}

<h2>Düzenle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Haberler</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.HaberlerID)

        <div class="form-group">
            @Html.LabelFor(model => model.Hbaslik, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hbaslik)
                @Html.ValidationMessageFor(model => model.Hbaslik)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hicerik, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hicerik)
                @Html.ValidationMessageFor(model => model.Hicerik)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Haberlere Geri Dön", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

projeOdev/projeOdev/Views/Haber/Index.cshtml
@model PagedList.IPagedList<projeOdev.Models.Haberler>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Haberler";
}

<h2>Haberler</h2>

<p>
    @Html.ActionLink("Haber Ekle", "Create")
</p>
@using (Html.BeginForm("Index", "Haber", FormMethod.Get))
{
    <p>
        Başlığa, İçeriğe Göre Arama : @Html.TextBox("Arama", ViewBag.CurrentFilter as string)
        <input type="submit" value="Ara" />
    </p>
}

<table class="table">
    <tr>
        <th>

            @Html.ActionLink("Haber Başlığı", "Index", new { siralama = ViewBag.NameSortParm })
            @*@Html.DisplayNameFor(model => model.Hbaslik)*@
        </th>
        <th>
            Haberin İçeriği
            @*@Html.ActionLink("Haber İçeriği", "Index", new { siralama = ViewBag.NameSortParm })*@
            @*@Html.DisplayNameFor(model => model.Hicerik)*@
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Hbaslik)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hicerik)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", new { id = item.HaberlerID }) |
                @Html.ActionLink("Detaylar", "Details", new { id = item.HaberlerID }) |
                @Html.ActionLink("Sil", "Delete", new { id = item.HaberlerID })
            </td>
        </tr>
    }

</table>
<br /> Sayfa @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))